#!/bin/bash

app_id="${1}"
new_fqdn="${2}"

if [[ ! -z $AZURE_USER ]] && [[ ! -z $AZURE_PASSWORD ]]
then
    az login --service-principal \
       --allow-no-subscriptions \
       -t "1c2154bf-3a88-413a-8407-0fd3dd69d216" \
       -u "${AZURE_USER}" \
       -p "${AZURE_PASSWORD}" >/dev/null

    function finish {
        az logout
    }
    trap finish EXIT
fi

app="$(az ad app show --id ${app_id})"

function urls() {
    echo ${app} | jq -r '.replyUrls | join("\n")'
}

if [[ $? == 0 ]]
then
  if urls | grep "${new_fqdn}" &>/dev/null
  then
      new_reply_urls="$(urls | grep -v "${new_fqdn}" | tr '\n' ' ')"

      az ad app update --id ${app_id} --reply-urls ${new_reply_urls}
  else
    echo "Already doesn't contain a reply url for '${new_fqdn}'"
  fi
else
  echo "App wasn't found"
  exit 1
fi
