#!/bin/bash

set -euo pipefail

app_id="${1}"
new_fqdn="${2}"

set +u
if [[ ! -z $AZURE_USER ]] && [[ ! -z $AZURE_PASSWORD ]]
then
    set -u
    az login --service-principal \
       --allow-no-subscriptions \
       -t "1c2154bf-3a88-413a-8407-0fd3dd69d216" \
       -u "${AZURE_USER}" \
       -p "${AZURE_PASSWORD}" >/dev/null

    function finish {
        exit_code=$?
        az logout
        exit $exit_code
    }
    trap finish EXIT
else
    set -u
fi

app="$(az ad app show --id ${app_id})"

if [[ $? == 0 ]]
then
  reply_urls="$(echo ${app} | jq -r '.replyUrls | join(" ")')"

  if echo "${reply_urls}" | grep "${new_fqdn}" &>/dev/null
  then
    echo "Already contains a reply url for '${new_fqdn}'"
  else
    new_reply_urls="${reply_urls} https://${new_fqdn}/oauth2/callback"

    az ad app update --id ${app_id} --reply-urls ${new_reply_urls}
  fi
else
  echo "App wasn't found"
  exit 1
fi
